### ISSUE TITLE
Try using fetch ponyfilly to reduce bundle size

### ISSUE THREAD

**Issue by c0bra** [softvu/seniorvu-sdk#9]
Axios is like 2/3 of our library size.

Try using https://github.com/developit/unfetch as a replacement.

**Edit**: Forgot that this library has to work both in the browser and on the server. Axios might still be the best way forward.

**Comment by c0bra** [comment]
Not going to worry about this.

**Comment by emerzn** [comment]
Seems like a hasty decision
